name: dwelling-dev-env

services:
  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - '16686:16686'
      - '4317:4317'
    environment:
      COLLECTOR_OTLP_ENABLED: true

  postgres:
    image: postgres:17
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'dwelling'
      POSTGRES_PASSWORD: 'P@ssw0rdP@ssw0rd'
      POSTGRES_DB: 'dwelling'
